import { es as t } from './i18n';
export const micIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg>`;
const feather = `<svg viewBox="0 0 40 40" fill="none" stroke="currentColor"><path d="M8 34C18 21 17 8 34 4c-1 16-10 22-20 24M11 30L29 10M18 22l1-9M20 20l9-2" stroke-width="1.4"/></svg>`;
const controls = `<div class="speech-controls"><button id="mic" class="mic" aria-label="${t.mic}">${micIcon}</button><div><div id="state" role="status">${t.connecting}</div><p id="hint">${t.hint}</p></div><button id="interrupt" class="interrupt" disabled aria-label="${t.stop}">■ <span>${t.stop}</span></button></div><form id="chat-form"><input id="message" maxlength="2000" aria-label="${t.write}" placeholder="${t.placeholder}" autocomplete="off"/><button aria-label="${t.send}" title="${t.send}">↗</button></form>`;
const scene = `<div class="art-panel"><div class="art-top"><span>${t.artTitle}</span><span class="live-dot">${t.live}</span></div><div class="painting-frame"><div id="avatar"></div><div class="canvas-shade"></div></div><div class="art-caption"><span class="small-diamond">✦</span><div><h2>${t.portrait}</h2><p>${t.portraitSub}</p></div><span class="small-diamond">✦</span></div><div class="candle"><i></i><b></b></div></div>`;
const settingsPanel = `<section class="panel module-panel"><div class="section-label">01 / ${t.modules}</div><div class="selectors"><label>${t.face}<select id="face"><option value="portrait2d">${t.portraitOption}</option><option value="bust3d">${t.bustOption}</option></select></label><label>${t.voice}<select id="tts"><option value="mock">${t.mockOption}</option><option value="elevenlabs">ElevenLabs</option></select></label><label>${t.voiceId}<input id="voice-id" placeholder="${t.voiceId}" list="voices"/><datalist id="voices"><option value="warm"><option value="bright"></datalist></label><label>${t.model}<select id="llm"><option value="mock">${t.mockOption}</option><option value="anthropic">Anthropic · Claude</option></select></label><label>${t.modelId}<input id="model-id"/></label><label>${t.recognition}<select id="stt"><option value="mock">${t.mockOption}</option><option value="browser">${t.browserOption}</option></select></label></div><div id="module-status" class="module-status"></div></section>`;
const playbackPanel = `<section class="panel timeline-panel"><div class="section-label">02 / ${t.timeline}</div><div class="timeline-info"><span id="viseme">${t.viseme}: sil</span><span id="mood">${t.mood}: ${t.moods.warm}</span></div><canvas id="timeline" aria-label="${t.timeline}" height="160"></canvas><div id="timeline-time">0.00 s</div><p class="muted">${t.idleTimeline}</p></section><section class="panel"><div class="section-label">03 / ${t.latency}</div><div id="latencies" class="latencies">${[t.sttLatency,t.llmLatency,t.ttsLatency,t.firstAudio,t.totalLatency].map((label,i)=>`<div><span>${label}</span><strong id="lat-${i}">—</strong></div>`).join('')}</div></section><section class="panel"><div class="section-label">04 / ${t.transcript}</div><div id="transcript" class="transcript"><p class="muted">${t.emptyTranscript}</p></div></section><section class="panel"><div class="section-label">05 / ${t.logs}</div><ol id="logs" class="logs"></ol></section>`;

export const stopIcon = '<svg viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="6" width="12" height="12" rx="2"/></svg>';
export function renderApp(lab: boolean) {
 if (!lab) return `<main class="minimal"><div id="avatar"></div><button id="mic" class="mic" aria-label="${t.mic}" aria-describedby="mode-description" title="${t.mic}">${micIcon}</button><span id="state" class="sr-only" role="status">${t.connecting}</span><span id="mode-description" class="sr-only"></span><span id="notice" class="sr-only" role="alert" hidden></span></main>`;
 return `<header class="site-header"><a class="brand" href="/">${feather}<span>${t.brand}<em>${t.brandAccent}</em></span></a><nav><a href="/">${t.salon}</a><a href="/lab" class="selected">${t.lab}</a><a href="/reports/">${t.evidence} ↗</a></nav><span class="header-edition">${t.established}</span></header><main class="lab-page"><div class="lab-heading"><p class="eyebrow">${t.labEyebrow}</p><h1>${t.labTitle}</h1><p>${t.labIntro}</p></div><div class="lab-grid"><div class="lab-preview">${scene}<div class="preview-controls"><div class="subtitle"><p id="subtitle"></p></div>${controls}<button class="phrase" id="test-phrase">${t.test} ↗</button></div></div><div class="lab-workbench">${settingsPanel}${playbackPanel}</div></div><div class="bottom-row"><span id="mode-badge" class="mode-badge">${t.mockHint}</span><button id="camera" class="camera" title="${t.cameraNote}">◎ ${t.camera}</button></div><div id="notice" class="notice" role="alert" hidden></div></main><footer><span>${t.footer}</span><span>${t.ai}</span></footer>`;
}
